// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0TA_5Tlq_LfidBDKouL2CdYEJoOehPxQ',
    appId: '1:616555807283:android:04249dc8d1478da9d3d946',
    messagingSenderId: '616555807283',
    projectId: 'rizz-dev-ccb51',
    storageBucket: 'rizz-dev-ccb51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD77lFn4PLsA4fDMBsxSj_0DAlBOFIxIVA',
    appId: '1:616555807283:ios:c2c821755596e2b1d3d946',
    messagingSenderId: '616555807283',
    projectId: 'rizz-dev-ccb51',
    storageBucket: 'rizz-dev-ccb51.appspot.com',
    androidClientId: '616555807283-1d19r9jbl8vlqq5n8q6ep3o03a9lf56b.apps.googleusercontent.com',
    iosClientId: '616555807283-rj9n78cjept6e25jet9jgm3bmfdccuu2.apps.googleusercontent.com',
    iosBundleId: 'com.example.rizz',
  );

}