// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'db/modals/user.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(2, 6810667852309190901),
      name: 'AppUser',
      lastPropertyId: const IdUid(9, 6578496897001385371),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 7201364966282132036),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 320870156517220331),
            name: 'uId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 6954266743099504584),
            name: 'email',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 4821538186021709762),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 6056671965920472618),
            name: 'snapId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 650115537996027714),
            name: 'age',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 4526376265618484965),
            name: 'gender',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 5336674238512703943),
            name: 'imageUrls',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 6578496897001385371),
            name: 'deviceToken',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(2, 6810667852309190901),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [4643737686930460596],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        9169436890928778469,
        273237302179965456,
        372890020861545965,
        3112333347511822020,
        1386536797943285672,
        6693019418257389854,
        2088031263258165785,
        4653640834308927323,
        7499113002254962779
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    AppUser: EntityDefinition<AppUser>(
        model: _entities[0],
        toOneRelations: (AppUser object) => [],
        toManyRelations: (AppUser object) => {},
        getId: (AppUser object) => object.id,
        setId: (AppUser object, int id) {
          object.id = id;
        },
        objectToFB: (AppUser object, fb.Builder fbb) {
          final uIdOffset = fbb.writeString(object.uId);
          final emailOffset = fbb.writeString(object.email);
          final nameOffset = fbb.writeString(object.name);
          final snapIdOffset = fbb.writeString(object.snapId);
          final genderOffset = fbb.writeString(object.gender);
          final imageUrlsOffset = fbb.writeString(object.imageUrls);
          final deviceTokenOffset = object.deviceToken == null
              ? null
              : fbb.writeString(object.deviceToken!);
          fbb.startTable(10);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uIdOffset);
          fbb.addOffset(2, emailOffset);
          fbb.addOffset(3, nameOffset);
          fbb.addOffset(4, snapIdOffset);
          fbb.addInt64(5, object.age);
          fbb.addOffset(6, genderOffset);
          fbb.addOffset(7, imageUrlsOffset);
          fbb.addOffset(8, deviceTokenOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final uIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final emailParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final snapIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final ageParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final genderParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 16, '');
          final imageUrlsParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 18, '');
          final deviceTokenParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 20);
          final object = AppUser(
              id: idParam,
              uId: uIdParam,
              name: nameParam,
              email: emailParam,
              snapId: snapIdParam,
              age: ageParam,
              gender: genderParam,
              imageUrls: imageUrlsParam,
              deviceToken: deviceTokenParam);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [AppUser] entity fields to define ObjectBox queries.
class AppUser_ {
  /// see [AppUser.id]
  static final id = QueryIntegerProperty<AppUser>(_entities[0].properties[0]);

  /// see [AppUser.uId]
  static final uId = QueryStringProperty<AppUser>(_entities[0].properties[1]);

  /// see [AppUser.email]
  static final email = QueryStringProperty<AppUser>(_entities[0].properties[2]);

  /// see [AppUser.name]
  static final name = QueryStringProperty<AppUser>(_entities[0].properties[3]);

  /// see [AppUser.snapId]
  static final snapId =
      QueryStringProperty<AppUser>(_entities[0].properties[4]);

  /// see [AppUser.age]
  static final age = QueryIntegerProperty<AppUser>(_entities[0].properties[5]);

  /// see [AppUser.gender]
  static final gender =
      QueryStringProperty<AppUser>(_entities[0].properties[6]);

  /// see [AppUser.imageUrls]
  static final imageUrls =
      QueryStringProperty<AppUser>(_entities[0].properties[7]);

  /// see [AppUser.deviceToken]
  static final deviceToken =
      QueryStringProperty<AppUser>(_entities[0].properties[8]);
}
